{% set name = "urdfdom_headers" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 76a68657c38e54bb45bddc4bd7d823a3b04edcd08064a56d8e7d46b9912035ac

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/include/urdf_model/model.h  # [unix]

    - if exist %PREFIX%\\Library\\CMake\\urdfdom_headers-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Headers for URDF parsers
  dev_url: https://github.com/ros/{{ name }}

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
