{% set name = "urdfdom_headers" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1acd50b976f642de9dc0fde532eb8d77ea09f4de12ebfbd9d88b0cd2891278fd
  patches:
    - msvc_include.patch  # [win]
    - 72.patch

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - pkg-config --exists --print-errors --debug {{ name }}
    - pkg-config --validate --print-errors --debug {{ name }}
    - test -f $PREFIX/include/urdfdom_headers/urdf_model/model.h  # [unix]

    - if exist %PREFIX%\\Library\\CMake\\urdfdom_headers-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Headers for URDF parsers
  dev_url: https://github.com/ros/{{ name }}

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
    - traversaro
