{% set name = "urdfdom_headers" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e12db588ccce52958264f6e4363ca642ab86c328c372e925681a12f7c39d963a
  patches:
    - msvc_include.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - pkg-config --exists --print-errors --debug {{ name }}
    - pkg-config --validate --print-errors --debug {{ name }}
    - test -f $PREFIX/include/urdf_model/model.h  # [unix]

    - if exist %PREFIX%\\Library\\CMake\\urdfdom_headers-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Headers for URDF parsers
  dev_url: https://github.com/ros/{{ name }}

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - traversaro
