{% set name = "urdfdom_headers" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2b3040a5f4d1e421b32d80540dd1d09fa0ef46c1d4152210ca8753c462b90e31
  patches:
    - relocatable-fix.patch

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/include/urdf_model/model.h  # [unix]

    - if exist %PREFIX%\\Library\\CMake\\urdfdom_headers-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Headers for URDF parsers'
  dev_url: https://github.com/ros/{{ name }}

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
