schema_version: 1

context:
  name: urdfdom_headers
  version: 1.1.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ros/${{ name }}/archive/${{ version }}.tar.gz
  sha256: 7602e37c6715fbf4cec3f0ded1e860157796423dc79da062a0e5ccb1226dc8e6
  patches:
    - if: win
      then: msvc_include.patch

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then: make

tests:
  - requirements:
      run:
        - pkg-config
    script:
      - pkg-config --modversion ${{ name }}
      - pkg-config --exists --print-errors --debug ${{ name }}
      - pkg-config --validate --print-errors --debug ${{ name }}
      - if: unix
        then: test -f $PREFIX/include/urdf_model/model.h
      - if: win
        then: if exist %PREFIX%\\Library\\CMake\\urdfdom_headers-config.cmake (exit 0) else (exit 1)

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Headers for URDF parsers
  homepage: http://github.com/ros/${{ name }}
  repository: https://github.com/ros/${{ name }}

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - traversaro
