travis:
  secure:
    BINSTAR_TOKEN: zptPT4EX+GQjOWF/XHn4QNkLfcFzMxioQs5l5VZysxtyMfKnikZexjsTT8zovXom0N7bnEo/UlyixTUb06EscgpfFklzqLXLzMjeUyAPFUBTARSuoAOAkmMkwduoyjZEXIT5N1oAPvkAveSaiz6NlHfQlFATMk+lILRq2iIX5IjsKLRRX4uvz3clBKcTHsa6boObNVb4RYU6LJ12aC+pdazNIK6SYalLiKMQnaztooZ/RH8s8ufaZ0+9Sxpps4MkjgS72MKI9uOZWqMK9WoTsPPoKqIG8Jin3+/FrwSjv7+Eh7Z/TEBHgRyDBWPLibQNl3oVD72OioygtqQS11th6Jsb4MRGQuWuEMayjxvuPDhFnq7f+1ne903HCL0GY0O7yoLTPH4SwWl0/u8PYufeITSwoeltj2H0f2IB6WYZdHUBf1VfWqkrPvPVkMDHWJuAIeISBRbGhF44pKvejXkqcOyEVfoXrAvAnK8fUTLzc+s2S+VxGiT/HtV4nfszw7dTRe8Ui7OU9San7sT/SXzC3HytvBsXH6aUnHnzesWYKXGRT99upjhuNMH1kHOXWcWQrrzNWXxqb9eBHfQLCioRlkJ+GBLY98i19Pm5tkVOibe/JFmzbCGrNdI3t/IeUExizJqdzZf5re6PEB3YIm/vop+XbQoxWxy4eWGcBUivKfg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
